- python/Array/array_union_intersection.py
- python/Array/cyclic_rotate.py
- python/Array/factorial.py
- python/Array/kth_min_max_elements.py
- python/Array/largest_subarray_sum.py
- python/Array/merge_intervals.py
- python/Array/min_max_elements_array.py
- python/Array/move_negatives.py
- python/Array/reverse_array.py
- python/Array/sort_array.py
- python/readme.md
- python/sample.txt
Add solutions to following questions (all from `Array` topic) - 
1. [`Reverse the Array`](https://www.geeksforgeeks.org/write-a-program-to-reverse-an-array-or-string/)
2. [`Find the maximum and minimum element in an array`](https://www.geeksforgeeks.org/maximum-and-minimum-in-an-array/)
3. [`Find the 'K-th' max and min elements of an array`](https://practice.geeksforgeeks.org/problems/kth-smallest-element/0)
4. [`Sort array consisting of [0, 1, 2]`](https://practice.geeksforgeeks.org/problems/sort-an-array-of-0s-1s-and-2s/0)
5. [`Move all negative elements to one side of array`](https://www.geeksforgeeks.org/move-negative-numbers-beginning-positive-end-constant-extra-space/)
6. [`Union and Intersection of 2 Sorted Arrays`](https://practice.geeksforgeeks.org/problems/union-of-two-arrays/0) …
> Add Python solutions to 10 questions

- c++/array/0,1,2_sort_array.cpp
- c++/array/max_and_min_in_array.cpp
Added "Find the maximum and minimum element in an array" in C++ using 3 approaches.
> Added 3rd and 4th questions in C++

- c++/array/Best Time to Buy and Sell Stock.cpp
- c++/array/Factorials of large numbers.cpp
- c++/array/Find the Duplicate Number( through Binary search).cpp
- c++/linkedlist/Middle of the Linked List.cpp
- c++/matrix/Search a 2D Matrix.cpp
- c++/string/Reverse String.cpp
1)buy and sell stocks
2)factorial of large number
3)find duplicate number
4)middle of linked list
5)search a 2d matrix
6)reverse a string
will add other c++ programs soon
> added c++ programs

- c++/array/Reverse an array
Created program to reverse an array using c++
> Reverse an array c++

- c++/array/Kth smallest element.cpp
Tried to write "Kth" max-min element in C++ using Quick Sort to reduce the time complexity.
> Kth smallest element using Quick sort

- python/String/Palindrome_or_not.py
- python/String/Reverse_a_string.py
- python/String/duplicates.py
- python/readme.md
3 new programs added in string section of python
> Proper file structure created

- c++/bit manipulation/binary code to intege.cpp
- c++/bit manipulation/even or odd using bit manipulation.cpp
- c++/bit manipulation/integer_to_binary.cpp
three codes have been added in the bit manipulation folder of C++
> added three new codes in bit manipulation folder - integer to binary, binary code to integer, even or odd using bit manipulation 

- c++/array/cyclically rotate.cpp
- c++/array/move all negative.cpp
Program to cyclically rotate array by one, using inbuilt function.
> Program to cyclically rotate array.

- Java/array/kthmaxmin.java
This is the other efficient method using priority queue
> Using Priority Queue

- Java/array/reversearray.java
I AM WRITING NEW CODE CAUSE IT'S NOT PASSING ALL TEST AS THERE IS SOME LOGICAL MISTAKES.
> there is eror in code

- .vscode/settings.json
- c++/searching & sorting/find fixed point (value equals to index).cpp
> Find Fixed point (value equals to index) in array.cpp

- Java/array/rearrangeArray.java
Time Complexity: O(n)
Space Complexity: O(1)
> added rearrange array in alternating +ve and -ve

- Java/array/medianSortArrSameSize.java
Problem Link: https://www.geeksforgeeks.org/median-of-two-sorted-arrays/
Time: O(logn)
Space: O(1)
> added solution of median of two sorted array of same size

- c++/matrix/Search a 2D Matrix.cpp
A approach using using binary search on the whole matrix.
> Update Search a 2D Matrix.cpp

- python/Array/1_array_reverse.py
python program for the reversing the array
> 1_array_reverse.py

- Java/array/Space optimization using bit manipulations.java
OUTPUT:-
MULTIPLES of 2 and 5:
2 4 5 6 8 10
> Space optimization using bit manipulations.java

- c++/bit manipulation/Bit Difference.cpp
- Question Link: https://practice.geeksforgeeks.org/problems/bit-difference/0
> Added Code for Bit Difference Question.

- python/Array/Kadane_algo.py
Kadane's Algo question solved in Python.
> Kadane's algo 

- c++/matrix/matrixTranspose.cpp
> MatrixTranspose

- Recursion_Examples/Factorial.py
- Recursion_Examples/Nth_Fibonacci_Number.java
**I have added some examples in Java and Python. Please check it and please merge it**. 
And If any kind of solution If you are finding then please let me know. If It is possible to answer it, I am ready to help you.
> Added Recursion Examples in Java and Python

- Java/strings/balanceparenthisis.java
Replaced For Loop to If-Else Loop for better Readability of code
Replaced List Methods with Stack Methods For Homogeneity of the Program 
Looking Forward For Merge
> Updated balanceparenthesis.java

- Java/LinkedList/LLasStack.java
Added the problem statement for the given solution
> Problem statement added for given solution

- Java/heap/MinMachineScheduledTasks.java
Program: Given a set of n number of tasks, implement a task scheduler method, tasks(), to run in O(n logn) time that finds the minimum number of machines required to complete these n tasks.
Constraints:
Task start time ≤ Task end time
> Program added for Scheduling Tasks on Minimum Machines

- python/Array/36_positiveNegative.py
- python/readme.md
Question 20 From 450-DSA Questions:  Arrange elements in alternate positive and negative items
> Added Array Question in Python

- c++/linkedlist/hasCycle.cpp
- c++/linkedlist/intersectionOfTwoLinkedList.cpp
- c++/linkedlist/removeNodeFromEnd.cpp
I have added 3 c++ leetcode problems solutions
> Added Three C++ Solutions of Linked List
